name: ${project.name}
version: ${project.version}
description: ${project.description}
author: Ste3et_C0st
website: ${project.url}
depend: [FurnitureLib]
main: de.Ste3et_C0st.Furniture.Main.main
api-version: 1.13
